### ISSUE TITLE
Include managed memory support

### ISSUE THREAD

**Issue by pentschev** [gmarkall/nbep-7#1]
It seems that no [managed memory](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1gd228014f19cc0975ebe3e0dd2af6dd1b) support was taken into consideration, possibly because Numba doesn't support that today, should we include that too?

**Comment by gmarkall** [comment]
Indeed, it is not yet supported in Numba: https://github.com/numba/numba/issues/4362

I think I'd find it difficult to take it into consideration without Numba supporting it already, but will give it some thought.

**Comment by pentschev** [comment]
Yeah, that makes sense to me, I just wanted to be sure that this was at least planned for the future. I will go ahead and close this for now until we have support for managed memory in Numba. Thanks @gmarkall !

**Comment by gmarkall** [comment]
Thanks - I've added a mention of managed memory and its lack of support in Numba, because it otherwise does leave the question open.
