### ISSUE TITLE
Relaxing (hard) Numba requirement

### ISSUE THREAD

**Issue by jakirkham** [gmarkall/nbep-7#11]
Some external implementers of this API may not want to make Numba a hard requirement, but may still want Numba to use their preferred allocator. What is the best way for us to address this need?

**Comment by gmarkall** [comment]
Would suggesting something like:

```python
try:
    import numba
    print("Setting Numba to use our memory manager")
    numba.cuda.cudadrv.driver.set_memory_manager(MyNumbaMemoryManager)
except ImportError:
    print("Numba not importable - do nothing")
```

be reasonable?

**Comment by jakirkham** [comment]
Where would `MyNumbaMemoryManager` be defined in this case? Does it need to inherit from anything in Numba?

**Comment by gmarkall** [comment]
`MyNumbaMemoryManager` will be a subclass of `BaseCUDAMemoryManager`, so it is inheriting from something in Numba - its definition would also need to be guarded in the `try ... except ImportError` (or could perhaps be defined in a module that is only imported if Numba is successfully imported).

**Comment by leofang** [comment]
I asked this in cupy/cupy#2976 because I thought it'd not be easy to test this plugin in 3rd party libraries' CIs. But I found that in `setup.py` one could specify the test time dependencies via `tests_require`, so perhaps this could be recommended in the NBEP for the purpose of setting up CIs?

**Comment by gmarkall** [comment]
@leofang thanks for bringing this up - just to make sure I'm understanding correctly: is the idea that the NBEP should recommend that in the `setup.py` of a third-party library, `tests_require` should include Numba so that:

* Any plugin implementations can be tested without going to a lot of trouble to include Numba in the test environment,
* without forcing Numba to become a hard dependency of the project as far as installation / packaging is concerned?

**Comment by leofang** [comment]
Yeah that sounds about right. And it's only a recommendation, not a required action. Most likely the adopting libraries will do so with `tests_require`, but perhaps some would not for other reasons that I can't think of right now.

**Comment by jakirkham** [comment]
Yeah we probably don't need to prescribe how people add the test dependency, but merely recommend that they include Numba in their testing.

**Comment by gmarkall** [comment]
Closing this issue as I'm adding details to the text now.
