### ISSUE TITLE
Discussion on considering async behavior including streams

### ISSUE THREAD

**Issue by gmarkall** [gmarkall/nbep-7#14]
Discussion moved from https://github.com/numba/numba/issues/4933#issuecomment-578088647:

> To make NBEP 7 more acceptable, it'd be better to consider the async behavior by including streams. (My impractical wish was to also solve the issue https://github.com/numba/numba/issues/4797 along this discussion, but it'd be too much work and trouble...)

**Comment by gmarkall** [comment]
@leofang The plan would is to eventually get to a point where async behaviour and streams are considered in some way in the External Memory Management plugin API - for a first step though, I'm keen to stick just to synchronous behaviour so as to keep the scope and implementation as small and simple as possible.

With regard to making NBEP 7 more acceptable (I think to some extent you're referring to this in the context of e.g. CuPy, and I think I recall you asking previously why a CuPy developer / user would be interested somewhere) - I've hopefully ensured that post-NBEP-7, nothing changes for a user / developer who has no interest in it or need for it - for those users, the `NumbaCUDAMemoryManager` will be used internally which should have the same observable behaviour as the existing logic which is coded into the `Context` class.

I have already implemented a plugin using the CuPy memory pool, which can exist entirely outside the CuPy source repository / implementation (see https://github.com/gmarkall/nbep-7/blob/master/nbep7/cupy_mempool.py ) - the aim would be not to force any changes on other libraries and frameworks in the ecosystem that have no interest in it (of course, if it does provide benefits then there should be no issues in integrating code for an EMM plugin upstream in a library that wants to, with Numba as an optional extra as discussed in  #11).

With the above in mind - are there other reasons it could be less-than-acceptable to developers / users of other libraries?

**Comment by leofang** [comment]
Thank you, Graham, for laying out your thoughts. I quite agree with what you said:
> I'm keen to stick just to synchronous behaviour so as to keep the scope and implementation as small and simple as possible.

and 
>  I've hopefully ensured that post-NBEP-7, nothing changes for a user / developer who has no interest in it or need for it 

When I raised the acceptability issue, I was simply worrying that libraries like TF that rely on async behaviors may not be willing to adopt NBEP-7. But this may likely be a false alert simply because of what you just said: Since this NBEP is sticking to sync behavior, it just won't be used in those libraries. Plus, as long as we don't push the plugin to upstream, there's no reason for the library maintainers to be unhappy with it. So for now I don't have further "objections". (To be fair I never had any, I was just trying to envision possible pushbacks. Sorry if I made myself a nuisance to you 😛)

**Comment by gmarkall** [comment]
Thanks for the clarifications, and for thinking about possible pushbacks - I am keen to be in anticipation of as many things that will cause blockers / issues for other libraries in the ecosystem.

I think you're right that libraries that rely on async behaviours probably won't use NBEP 7 to implement a memory management plugin for now -  assuming there is a need for it in the future, I hope to revisit async with external memory management, probably after having looked into a bit more support for other stream functionality in Numba (for the CUDA array interface, and per-thread defaults)

I'll close this issue for now - many thanks for your time and thoughts!
