### ISSUE TITLE
Closing the IPC handle

### ISSUE THREAD

**Issue by pentschev** [gmarkall/nbep-7#2]
I noticed it is possible to open/get the IPC handle with `get_ipc_handle`, but it seems like closing that handle isn't considered. What is the expected way to close the handle?

Once you free CUDA memory (with `cudaFree`), but you still have the handle open in a different process, that memory will not be freed until the handle is closed. My concern is that you may get a handle from a different process and not be able to close it, thus causing the memory not to be freed until the application terminates, which is a major issue we see with UCX today that we're trying to fix it.

**Comment by gmarkall** [comment]
I should probably expand a bit more on why I didn't include closing an IPC handle in the plugin interface itself - The `IpcArrayHandle` object has a `close()` method which can be called to close it: http://numba.pydata.org/numba-doc/latest/cuda/ipc.html?highlight=ipc#numba.cuda.cudadrv.devicearray.IpcArrayHandle.close. This eventually ends up calling `cuIpcCloseMemHandle`: https://github.com/numba/numba/blob/master/numba/cuda/cudadrv/driver.py#L1083. I had been assuming that this was sufficient for an IPC handle that came from any external library, but perhaps this isn't the case - can you foresee any situation where the IPC handle should be closed in a different way?

My thinking about this was guided somewhat by the existing RMM code, which provides a function for getting an IPC handle, but not for closing it - https://github.com/rapidsai/rmm/blob/branch-0.12/python/rmm/rmm.py#L254-L267 - I inferred from this that the `close()` method works correctly even if the IPC handle came from the RMM code.

**Comment by pentschev** [comment]
> can you foresee any situation where the IPC handle should be closed in a different way?

No, I think that covers it, I wasn't aware that Numba covered that internally, thanks for pointing that out!

> My thinking about this was guided somewhat by the existing RMM code, which provides a function for getting an IPC handle, but not for closing it - https://github.com/rapidsai/rmm/blob/branch-0.12/python/rmm/rmm.py#L254-L267 - I inferred from this that the close() method works correctly even if the IPC handle came from the RMM code.

Yeah, it looks like RMM simply uses that functionality from Numba, which handles closing of the IPC handle, as you pointed above.

That said, I don't think we need anything here. Thanks @gmarkall !

**Comment by gmarkall** [comment]
Thanks - I did add some description of the `IpcHandle` object and how it can be used to close the IPC handle, as others might have the same question upon reading the document.
