### ISSUE TITLE
Example usage vs Current implementation status code

### ISSUE THREAD

**Issue by pentschev** [gmarkall/nbep-7#3]
The [Example usage](https://github.com/pentschev/nbep-7#example-usage) section contains the exact same code/output as the [Current implementation status](https://github.com/pentschev/nbep-7#current-implementation-status), but the latter mentions that the code should be "similar". Are code/output the same by accident, or should we be linking one section to the other instead?

**Comment by gmarkall** [comment]
It's an accident - each time the example is run, the pointers and timestamps would be expected to be different - from another re-run just now, I get:

```
$ python simple01.py 
Event Type,Device ID,Address,Stream,Size (bytes),Free Memory,Total Memory,Current Allocs,Start,End,Elapsed,Location
Alloc,0,0x7f96c7400000,0,80,0,0,1,1.13396,1.13576,0.00180059,/home/nfs/gmarkall/numbadev/numba/numba/cuda/cudadrv/driver.py:686
Free,0,0x7f96c7400000,0,0,0,0,0,1.13628,1.13723,0.000956004,/home/nfs/gmarkall/numbadev/numba/numba/utils.py:678
```

Really what I was trying to demonstrate was that the prototype works for this use case in the same way as the design documented above. I did need to use the prototype to generate the example output that is mentioned first, anyway - perhaps it would be less confusing not to show a second set of output from the prototype.

**Comment by gmarkall** [comment]
I've now updated the output from the prototype with something that varies from the earlier example and clarified what it's showing - I think this addresses the potential confusion that the repetition caused, so I'll close the issue, but please let me know if it still needs work to clarify it.

Many thanks!

**Comment by pentschev** [comment]
Thanks @gmarkall !
