### ISSUE TITLE
CuPy pool allocator

### ISSUE THREAD

**Issue by pentschev** [gmarkall/nbep-7#5]
This is an attempt at answering the "What about CuPy's pool allocator?" question from [Unresolved items](https://github.com/pentschev/nbep-7#unresolved-items).

It seems that CuPy keeps a [`MemoryPool` object](https://github.com/cupy/cupy/blob/master/cupy/cuda/memory.pyx#L1213-L1239) with [one memory pool per GPU as a collection](https://github.com/cupy/cupy/blob/master/cupy/cuda/memory.pyx#L1244-L1245).

**Comment by gmarkall** [comment]
Thanks! Will incorporate into the document.

**Comment by gmarkall** [comment]
Thanks! I've just added this info to the document.
