### ISSUE TITLE
Asynchronous memory allocation / free

### ISSUE THREAD

**Issue by kkraus14** [gmarkall/nbep-7#7]
There's thoughts about an asynchronous memory manager where an allocation or free could take a CUDA stream and execute asynchronously. For freeing I imagine that wouldn't necessarily be a big deal since it's under the hood in Python garbage collection, but for allocations this could be problematic if the user tries to then launch a kernel on the default stream from this asynchronous memory allocation.

May want to clarify that this is out of scope for this initial proposal or touch on how an asynchronous memory manager could be supported.

**Comment by gmarkall** [comment]
Thanks for the suggestion - I'll add mention of this to the document.

I think it's good to have in mind and be thinking about it for the future to plan what other changes might be needed to support it - there is some notion of a device array having a stream in Numba already, but the stream of the device array is the default stream in which operations on it will be performed if no stream is specified - this definition could be modified to be the stream in which it was allocated, depending on the impact that would have on existing supported use cases.

**Comment by gmarkall** [comment]
Added some notes around this in https://github.com/gmarkall/nbep-7/commit/0ed4d159daa40947a7564b976d8d298c50440af1.

Many thanks!
